// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: roundTest

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_okLight;
extern lv_obj_t * ui_timeLabel;
extern lv_obj_t * ui_heatPadContainer;
extern lv_obj_t * ui_heatpadTempLabel;
extern lv_obj_t * ui_tempSignLabel;
extern lv_obj_t * ui_heatpadIcon;
extern lv_obj_t * ui_wetplaceContainer;
extern lv_obj_t * ui_wetplaceTempLabel;
extern lv_obj_t * ui_wetplaceTempSignLabel;
extern lv_obj_t * ui_wetplaceTempIcon;
extern lv_obj_t * ui_wetplaceHumidityIcon;
extern lv_obj_t * ui_wetplaceHumidityLabel;
extern lv_obj_t * ui_warningLight;
extern lv_obj_t * ui_criticalLamp;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

