// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: roundTest

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_okLight = NULL;
lv_obj_t * ui_timeLabel = NULL;
lv_obj_t * ui_heatPadContainer = NULL;
lv_obj_t * ui_heatpadTempLabel = NULL;
lv_obj_t * ui_tempSignLabel = NULL;
lv_obj_t * ui_heatpadIcon = NULL;
lv_obj_t * ui_wetplaceContainer = NULL;
lv_obj_t * ui_wetplaceTempLabel = NULL;
lv_obj_t * ui_wetplaceTempSignLabel = NULL;
lv_obj_t * ui_wetplaceTempIcon = NULL;
lv_obj_t * ui_wetplaceHumidityIcon = NULL;
lv_obj_t * ui_wetplaceHumidityLabel = NULL;
lv_obj_t * ui_warningLight = NULL;
lv_obj_t * ui_criticalLamp = NULL;
// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_TOP, 300, 0, &ui_Screen3_screen_init);
    }
}
// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    //lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_okLight = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_okLight, 50);
    lv_obj_set_height(ui_okLight, 50);
    lv_obj_set_x(ui_okLight, 0);
    lv_obj_set_y(ui_okLight, 150);
    lv_obj_set_align(ui_okLight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_okLight, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_okLight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_okLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_okLight, lv_color_hex(0x00FFA0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_okLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_okLight, lv_color_hex(0x49FA7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_okLight, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_okLight, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_okLight, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_okLight, lv_color_hex(0x00FFA0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_okLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_okLight, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_okLight, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_okLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_okLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_timeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeLabel, 0);
    lv_obj_set_y(ui_timeLabel, -100);
    lv_obj_set_align(ui_timeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeLabel, "--:--");
    lv_obj_set_style_text_color(ui_timeLabel, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_heatPadContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_heatPadContainer);
    lv_obj_set_width(ui_heatPadContainer, 268);
    lv_obj_set_height(ui_heatPadContainer, 50);
    lv_obj_set_x(ui_heatPadContainer, 0);
    lv_obj_set_y(ui_heatPadContainer, 30);
    lv_obj_set_align(ui_heatPadContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_heatPadContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_heatpadTempLabel = lv_label_create(ui_heatPadContainer);
    lv_obj_set_width(ui_heatpadTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_heatpadTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_heatpadTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_heatpadTempLabel, "--");
    lv_obj_set_style_text_align(ui_heatpadTempLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_heatpadTempLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_heatpadTempLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempSignLabel = lv_label_create(ui_heatPadContainer);
    lv_obj_set_width(ui_tempSignLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempSignLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempSignLabel, 30);
    lv_obj_set_y(ui_tempSignLabel, 0);
    lv_obj_set_align(ui_tempSignLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempSignLabel, "°");
    lv_obj_set_style_text_font(ui_tempSignLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_heatpadIcon = lv_image_create(ui_heatPadContainer);
    lv_image_set_src(ui_heatpadIcon, &ui_img_237497367);
    lv_obj_set_width(ui_heatpadIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_heatpadIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_heatpadIcon, -70);
    lv_obj_set_y(ui_heatpadIcon, 0);
    lv_obj_set_align(ui_heatpadIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_heatpadIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_heatpadIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wetplaceContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_wetplaceContainer);
    lv_obj_set_width(ui_wetplaceContainer, 268);
    lv_obj_set_height(ui_wetplaceContainer, 50);
    lv_obj_set_x(ui_wetplaceContainer, 0);
    lv_obj_set_y(ui_wetplaceContainer, -10);
    lv_obj_set_align(ui_wetplaceContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_wetplaceContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wetplaceTempLabel = lv_label_create(ui_wetplaceContainer);
    lv_obj_set_width(ui_wetplaceTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wetplaceTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wetplaceTempLabel, -35);
    lv_obj_set_y(ui_wetplaceTempLabel, 3);
    lv_obj_set_align(ui_wetplaceTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wetplaceTempLabel, "--");
    lv_obj_set_style_text_align(ui_wetplaceTempLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_wetplaceTempLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wetplaceTempLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wetplaceTempSignLabel = lv_label_create(ui_wetplaceContainer);
    lv_obj_set_width(ui_wetplaceTempSignLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wetplaceTempSignLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wetplaceTempSignLabel, -5);
    lv_obj_set_y(ui_wetplaceTempSignLabel, 0);
    lv_obj_set_align(ui_wetplaceTempSignLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wetplaceTempSignLabel, "°");
    lv_obj_set_style_text_font(ui_wetplaceTempSignLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wetplaceTempIcon = lv_image_create(ui_wetplaceContainer);
    lv_image_set_src(ui_wetplaceTempIcon, &ui_img_8884449);
    lv_obj_set_width(ui_wetplaceTempIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wetplaceTempIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wetplaceTempIcon, -80);
    lv_obj_set_y(ui_wetplaceTempIcon, 0);
    lv_obj_set_align(ui_wetplaceTempIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wetplaceTempIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_wetplaceTempIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wetplaceHumidityIcon = lv_image_create(ui_wetplaceContainer);
    lv_image_set_src(ui_wetplaceHumidityIcon, &ui_img_1662018118);
    lv_obj_set_width(ui_wetplaceHumidityIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wetplaceHumidityIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wetplaceHumidityIcon, 15);
    lv_obj_set_y(ui_wetplaceHumidityIcon, 0);
    lv_obj_set_align(ui_wetplaceHumidityIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wetplaceHumidityIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_wetplaceHumidityIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wetplaceHumidityLabel = lv_label_create(ui_wetplaceContainer);
    lv_obj_set_width(ui_wetplaceHumidityLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wetplaceHumidityLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wetplaceHumidityLabel, 50);
    lv_obj_set_y(ui_wetplaceHumidityLabel, 3);
    lv_obj_set_align(ui_wetplaceHumidityLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wetplaceHumidityLabel, "--");
    lv_obj_set_style_text_align(ui_wetplaceHumidityLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_wetplaceHumidityLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wetplaceHumidityLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_warningLight = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_warningLight, 50);
    lv_obj_set_height(ui_warningLight, 50);
    lv_obj_set_x(ui_warningLight, 0);
    lv_obj_set_y(ui_warningLight, 150);
    lv_obj_set_align(ui_warningLight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_warningLight, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_warningLight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_warningLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_warningLight, lv_color_hex(0x00FFA0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_warningLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_warningLight, lv_color_hex(0x49FA7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_warningLight, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_warningLight, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_warningLight, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_warningLight, lv_color_hex(0xFFAB0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_warningLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_warningLight, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_warningLight, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_warningLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_warningLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_criticalLamp = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_criticalLamp, 50);
    lv_obj_set_height(ui_criticalLamp, 50);
    lv_obj_set_x(ui_criticalLamp, 0);
    lv_obj_set_y(ui_criticalLamp, 150);
    lv_obj_set_align(ui_criticalLamp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_criticalLamp, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_criticalLamp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_criticalLamp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_criticalLamp, lv_color_hex(0x00FFA0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_criticalLamp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_criticalLamp, lv_color_hex(0x49FA7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_criticalLamp, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_criticalLamp, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_criticalLamp, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_criticalLamp, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_criticalLamp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_criticalLamp, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_criticalLamp, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_criticalLamp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_criticalLamp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_okLight = NULL;
    ui_timeLabel = NULL;
    ui_heatPadContainer = NULL;
    ui_heatpadTempLabel = NULL;
    ui_tempSignLabel = NULL;
    ui_heatpadIcon = NULL;
    ui_wetplaceContainer = NULL;
    ui_wetplaceTempLabel = NULL;
    ui_wetplaceTempSignLabel = NULL;
    ui_wetplaceTempIcon = NULL;
    ui_wetplaceHumidityIcon = NULL;
    ui_wetplaceHumidityLabel = NULL;
    ui_warningLight = NULL;
    ui_criticalLamp = NULL;

}
