// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: roundTest

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern void ui_event_ArcPUMP(lv_event_t * e);
extern lv_obj_t * ui_ArcPUMP;
extern lv_obj_t * ui_labelPumpInit;
extern lv_obj_t * ui_labelPumpPower;
extern lv_obj_t * ui_dropdownPwmFreq;
extern lv_obj_t * ui_switchOnOffPump;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

