// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: roundTest

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Spinner1 = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_opa(ui_Screen2, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_Image4, &ui_img_1242781495);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, 0);
    lv_obj_set_y(ui_Image4, 30);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner1 = lv_spinner_create(ui_Screen2);
    //lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 50);
    lv_obj_set_height(ui_Spinner1, 50);
    lv_obj_set_x(ui_Spinner1, 0);
    lv_obj_set_y(ui_Spinner1, -40);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Spinner1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xBEBEBE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Image4 = NULL;
    ui_Spinner1 = NULL;

}
