// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: roundTest

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern void ui_event_RollerMenu(lv_event_t * e);
extern lv_obj_t * ui_RollerMenu;
extern lv_obj_t * ui_ButtonRollerUp;
extern lv_obj_t * ui_LabelUp;
extern lv_obj_t * ui_ButtonRollerDown;
extern lv_obj_t * ui_MoistureContainer;
extern lv_obj_t * ui_SwitchMoistOnOff;
extern lv_obj_t * ui_SliderPumpPower;
extern lv_obj_t * ui_LableMoistureCurrent;
extern lv_obj_t * ui_SliderMoistureVolume;
extern lv_obj_t * ui_LabelMoistPrecentSign;
extern lv_obj_t * ui_LableMoistureTraget;
extern void ui_event_ArcMoistLevel(lv_event_t * e);
extern lv_obj_t * ui_ArcMoistLevel;
extern lv_obj_t * ui_HeaterContainer;
extern void ui_event_ArcHeatLevel(lv_event_t * e);
extern lv_obj_t * ui_ArcHeatLevel;
extern lv_obj_t * ui_SwitchHeaterOnOff;
extern lv_obj_t * ui_LabelCurrent1;
extern lv_obj_t * ui_LabelSetpoint;
extern lv_obj_t * ui_LabelTempSetpoint;
extern lv_obj_t * ui_LabelTempCurrent;
extern lv_obj_t * ui_FeederContainer;
extern lv_obj_t * ui_LightContainer;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

