// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: roundTest

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern void ui_event_ArcMoistLevel(lv_event_t * e);
extern lv_obj_t * ui_ArcMoistLevel;
extern void ui_event_Roller2(lv_event_t * e);
extern lv_obj_t * ui_Roller2;
extern lv_obj_t * ui_ButtonRollerUp;
extern lv_obj_t * ui_LabelUp;
extern lv_obj_t * ui_ButtonRollerDown;
extern lv_obj_t * ui_LabelDown;
extern lv_obj_t * ui_SwitchMoistOnOff;
extern lv_obj_t * ui_LabelMoistOnOff;
extern lv_obj_t * ui_LableMoistureTraget;
extern lv_obj_t * ui_LabelMoistPrecentSign;
extern lv_obj_t * ui_SliderMoistureVolume;
extern lv_obj_t * ui_SliderPumpPower;
extern lv_obj_t * ui_LableMoistureCurrent;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

