// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: roundTest

#ifndef _ROUNDTEST_UI_H
#define _ROUNDTEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
#include <freertos/FreeRTOS.h>
#include <freertos/semphr.h>

void animBtnClick_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
void ui_event_arcTempSettings(lv_event_t * e);
extern lv_obj_t * ui_arcTempSettings;
extern lv_obj_t * ui_hidePanel;
void ui_event_btnIncrease(lv_event_t * e);
extern lv_obj_t * ui_btnIncrease;
extern lv_obj_t * ui_tempLabel;
void ui_event_btnDecrease(lv_event_t * e);
extern lv_obj_t * ui_btnDecrease;
extern lv_obj_t * ui_labelActTemp;
extern lv_obj_t * ui_Button1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
void ui_event_ArcPUMP(lv_event_t * e);
extern lv_obj_t * ui_ArcPUMP;
extern lv_obj_t * ui_labelPumpInit;
extern lv_obj_t * ui_labelPumpPower;
extern lv_obj_t * ui_dropdownPwmFreq;
extern lv_obj_t * ui_switchOnOffPump;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
void ui_event_ArcMoistLevel(lv_event_t * e);
extern lv_obj_t * ui_ArcMoistLevel;
extern lv_obj_t * ui_Roller2;
extern lv_obj_t * ui_ButtonRollerUp;
extern lv_obj_t * ui_LabelBtnUp;
extern lv_obj_t * ui_ButtonRollerUp1;
extern lv_obj_t * ui_LabelBtnDown;
extern lv_obj_t * ui_SwitchMoistOnOff;
extern lv_obj_t * ui_LabelMoistOnOff;
extern lv_obj_t * ui_LableMoisture;
extern lv_obj_t * ui_LabelMoistPrecentSign;
extern lv_obj_t * ui_SlidetMoistureVolume;
extern lv_obj_t * ui_SliderPumpPower;
extern lv_obj_t * ui_LabelActualMoist;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1687522520);    // assets/+3232.png
LV_IMG_DECLARE(ui_img_699983090);    // assets/-3232.png
LV_IMG_DECLARE(
    ui_img_water_drop_24dp_d9d9d9_fill0_wght600_grad0_opsz24_png);    // assets/water_drop_24dp_D9D9D9_FILL0_wght600_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_bolt_24dp_d9d9d9_fill0_wght600_grad0_opsz24_png);    // assets/bolt_24dp_D9D9D9_FILL0_wght600_GRAD0_opsz24.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif
extern SemaphoreHandle_t gui_mutex;
#endif
