// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: roundTest

#ifndef _ROUNDTEST_UI_H
#define _ROUNDTEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include <freertos/FreeRTOS.h>
#include <freertos/semphr.h>

///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen2.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * animBtnClick_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_237497367);    // assets/bath_outdoor_24dp_F19E39_FILL0_wght600_GRAD-25_opsz24 (1).png
LV_IMG_DECLARE(ui_img_8884449);    // assets/spa_24dp_78A75A_FILL0_wght600_GRAD-25_opsz24 (1).png
LV_IMG_DECLARE(ui_img_1662018118);    // assets/dew_point_24dp_5985E1_FILL0_wght400_GRAD0_opsz24 (1).png
LV_IMG_DECLARE(ui_img_up_png);    // assets/up.png
LV_IMG_DECLARE(ui_img_down_png);    // assets/down.png
LV_IMG_DECLARE(ui_img_bolt1_png);    // assets/bolt1.png
LV_IMG_DECLARE(ui_img_water1_png);    // assets/water1.png
LV_IMG_DECLARE(ui_img_1242781495);    // assets/liz (1) (2) (1).png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif
extern SemaphoreHandle_t gui_mutex;
#endif
