// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: roundTest

#include "ui.h"


// COMPONENT switchPelPowerPolarity

lv_obj_t * ui_switchPelPowerPolarity_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_switchPelPowerPolarity;
    cui_switchPelPowerPolarity = lv_switch_create(comp_parent);
    lv_obj_set_width(cui_switchPelPowerPolarity, 50);
    lv_obj_set_height(cui_switchPelPowerPolarity, 25);
    lv_obj_set_x(cui_switchPelPowerPolarity, -118);
    lv_obj_set_y(cui_switchPelPowerPolarity, -5);
    lv_obj_set_align(cui_switchPelPowerPolarity, LV_ALIGN_CENTER);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_SWITCHPELPOWERPOLARITY_NUM);
    children[UI_COMP_SWITCHPELPOWERPOLARITY_SWITCHPELPOWERPOLARITY] = cui_switchPelPowerPolarity;
    lv_obj_add_event_cb(cui_switchPelPowerPolarity, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_switchPelPowerPolarity, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_switchPelPowerPolarity_create_hook(cui_switchPelPowerPolarity);
    return cui_switchPelPowerPolarity;
}

