// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: roundTest

#ifndef _UI_COMP_SWITCHPELPOWERPOLARITY_H
#define _UI_COMP_SWITCHPELPOWERPOLARITY_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT switchPelPowerPolarity
#define UI_COMP_SWITCHPELPOWERPOLARITY_SWITCHPELPOWERPOLARITY 0
#define _UI_COMP_SWITCHPELPOWERPOLARITY_NUM 1
lv_obj_t * ui_switchPelPowerPolarity_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
