// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: roundTest

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Roller2 = lv_roller_create(ui_Screen3);
    lv_roller_set_options(ui_Roller2, "FEEDER\nLIGHT\nHEATER\nMOISTURE", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller2, 50);
    lv_obj_set_width(ui_Roller2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller2, -55);
    lv_obj_set_y(ui_Roller2, 0);
    lv_obj_set_align(ui_Roller2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Roller2, LV_OBJ_FLAG_PRESS_LOCK);      /// Flags
    lv_obj_set_style_text_align(ui_Roller2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Roller2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Roller2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Roller2, 20, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller2, lv_color_hex(0x333333), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller2, 70, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Roller2, false, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_ButtonRollerUp = lv_button_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonRollerUp, 30);
    lv_obj_set_height(ui_ButtonRollerUp, 30);
    lv_obj_set_x(ui_ButtonRollerUp, -50);
    lv_obj_set_y(ui_ButtonRollerUp, -45);
    lv_obj_set_align(ui_ButtonRollerUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRollerUp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonRollerUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonRollerUp, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonRollerUp, lv_color_hex(0xD0D0D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonRollerUp, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_ButtonRollerUp);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, ">");

    ui_ButtonRollerUp1 = lv_button_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonRollerUp1, 30);
    lv_obj_set_height(ui_ButtonRollerUp1, 30);
    lv_obj_set_x(ui_ButtonRollerUp1, -50);
    lv_obj_set_y(ui_ButtonRollerUp1, 50);
    lv_obj_set_align(ui_ButtonRollerUp1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRollerUp1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonRollerUp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonRollerUp1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonRollerUp1, lv_color_hex(0xD0D0D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonRollerUp1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_ButtonRollerUp1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, ">");

    ui_SwitchMoistOnOff = lv_switch_create(ui_Screen3);
    lv_obj_set_width(ui_SwitchMoistOnOff, 50);
    lv_obj_set_height(ui_SwitchMoistOnOff, 25);
    lv_obj_set_x(ui_SwitchMoistOnOff, 85);
    lv_obj_set_y(ui_SwitchMoistOnOff, 0);
    lv_obj_set_align(ui_SwitchMoistOnOff, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SwitchMoistOnOff, lv_color_hex(0xFF8D01), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchMoistOnOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SwitchMoistOnOff, lv_color_hex(0x1AFF58), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SwitchMoistOnOff, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_SwitchMoistOnOff, lv_color_hex(0xD2D2D2), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchMoistOnOff, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SwitchMoistOnOff, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SwitchMoistOnOff, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SwitchMoistOnOff, 3, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelMoistOnOff = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelMoistOnOff, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMoistOnOff, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMoistOnOff, 43);
    lv_obj_set_y(ui_LabelMoistOnOff, 1);
    lv_obj_set_align(ui_LabelMoistOnOff, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMoistOnOff, "I / O");
    lv_obj_set_style_text_font(ui_LabelMoistOnOff, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableMoisture = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LableMoisture, 35);
    lv_obj_set_height(ui_LableMoisture, 22);
    lv_obj_set_x(ui_LableMoisture, 37);
    lv_obj_set_y(ui_LableMoisture, -54);
    lv_obj_set_align(ui_LableMoisture, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LableMoisture, "50");
    lv_obj_set_style_text_align(ui_LableMoisture, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableMoisture, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LableMoisture, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LableMoisture, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LableMoisture, 70, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcMoistLevel = lv_arc_create(ui_Screen3);
    lv_obj_set_width(ui_ArcMoistLevel, 200);
    lv_obj_set_height(ui_ArcMoistLevel, 200);
    lv_obj_set_x(ui_ArcMoistLevel, -2);
    lv_obj_set_y(ui_ArcMoistLevel, -2);
    lv_obj_set_align(ui_ArcMoistLevel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArcMoistLevel, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_arc_set_value(ui_ArcMoistLevel, 50);
    lv_arc_set_bg_angles(ui_ArcMoistLevel, 0, 80);
    lv_arc_set_rotation(ui_ArcMoistLevel, 260);
    lv_obj_set_style_arc_rounded(ui_ArcMoistLevel, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcMoistLevel, lv_color_hex(0x09DFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcMoistLevel, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcMoistLevel, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcMoistLevel, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcMoistLevel, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ArcMoistLevel, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ArcMoistLevel, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ArcMoistLevel, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ArcMoistLevel, LV_BORDER_SIDE_FULL, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelMoistPrecentSign = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelMoistPrecentSign, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMoistPrecentSign, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMoistPrecentSign, 2);
    lv_obj_set_y(ui_LabelMoistPrecentSign, -56);
    lv_obj_set_align(ui_LabelMoistPrecentSign, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMoistPrecentSign, "%");

    ui_ArcMoistPumpPower = lv_arc_create(ui_Screen3);
    lv_obj_set_width(ui_ArcMoistPumpPower, 200);
    lv_obj_set_height(ui_ArcMoistPumpPower, 200);
    lv_obj_set_align(ui_ArcMoistPumpPower, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArcMoistPumpPower, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_arc_set_value(ui_ArcMoistPumpPower, 50);
    lv_arc_set_bg_angles(ui_ArcMoistPumpPower, 0, 70);
    lv_arc_set_rotation(ui_ArcMoistPumpPower, 25);
    lv_obj_set_style_arc_rounded(ui_ArcMoistPumpPower, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcMoistPumpPower, lv_color_hex(0xEFFC00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcMoistPumpPower, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcMoistPumpPower, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcMoistPumpPower, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcMoistPumpPower, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ArcMoistPumpPower, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ArcMoistPumpPower, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ArcMoistPumpPower, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ArcMoistLevel, ui_event_ArcMoistLevel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}
