// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: roundTest

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ArcPUMP = lv_arc_create(ui_Screen2);
    lv_obj_set_width(ui_ArcPUMP, 210);
    lv_obj_set_height(ui_ArcPUMP, 210);
    lv_obj_set_align(ui_ArcPUMP, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcPUMP, 50);


    ui_labelPumpInit = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_labelPumpInit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPumpInit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPumpInit, 0);
    lv_obj_set_y(ui_labelPumpInit, -60);
    lv_obj_set_align(ui_labelPumpInit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPumpInit, "PUMP");
    lv_obj_set_style_text_font(ui_labelPumpInit, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPumpPower = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_labelPumpPower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPumpPower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPumpPower, 0);
    lv_obj_set_y(ui_labelPumpPower, -25);
    lv_obj_set_align(ui_labelPumpPower, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPumpPower, "00");
    lv_obj_set_style_text_color(ui_labelPumpPower, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPumpPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPumpPower, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dropdownPwmFreq = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_dropdownPwmFreq, "2500\n5000\n7500\n10000\n12500\n15000\n17500\n20000\n22500\n25000");
    lv_obj_set_width(ui_dropdownPwmFreq, 72);
    lv_obj_set_height(ui_dropdownPwmFreq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dropdownPwmFreq, 0);
    lv_obj_set_y(ui_dropdownPwmFreq, 20);
    lv_obj_set_align(ui_dropdownPwmFreq, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dropdownPwmFreq, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_switchOnOffPump = lv_switch_create(ui_Screen2);
    lv_obj_set_width(ui_switchOnOffPump, 60);
    lv_obj_set_height(ui_switchOnOffPump, 30);
    lv_obj_set_x(ui_switchOnOffPump, 0);
    lv_obj_set_y(ui_switchOnOffPump, 84);
    lv_obj_set_align(ui_switchOnOffPump, LV_ALIGN_CENTER);


    lv_obj_add_event_cb(ui_ArcPUMP, ui_event_ArcPUMP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
