// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: roundTest

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_arcTempSettings = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_arcTempSettings, 200);
    lv_obj_set_height(ui_arcTempSettings, 200);
    lv_obj_set_align(ui_arcTempSettings, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_arcTempSettings, 5, 80);
    lv_arc_set_value(ui_arcTempSettings, 25);
    lv_arc_set_bg_angles(ui_arcTempSettings, 180, 0);
    lv_obj_set_style_arc_rounded(ui_arcTempSettings, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arcTempSettings, lv_color_hex(0xC72C68), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcTempSettings, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arcTempSettings, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcTempSettings, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcTempSettings, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_arcTempSettings, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_arcTempSettings, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_arcTempSettings, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_hidePanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_hidePanel, 240);
    lv_obj_set_height(ui_hidePanel, 120);
    lv_obj_set_x(ui_hidePanel, 0);
    lv_obj_set_y(ui_hidePanel, 65);
    lv_obj_set_align(ui_hidePanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_hidePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_hidePanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hidePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_hidePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_hidePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_hidePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_hidePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnIncrease = lv_imagebutton_create(ui_Screen1);
    lv_imagebutton_set_src(ui_btnIncrease, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_1687522520, NULL);
    lv_imagebutton_set_src(ui_btnIncrease, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_1687522520, NULL);
    lv_imagebutton_set_src(ui_btnIncrease, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imagebutton_set_src(ui_btnIncrease, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imagebutton_set_src(ui_btnIncrease, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imagebutton_set_src(ui_btnIncrease, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_btnIncrease, 32);
    lv_obj_set_height(ui_btnIncrease, 32);
    lv_obj_set_x(ui_btnIncrease, 70);
    lv_obj_set_y(ui_btnIncrease, 55);
    lv_obj_set_align(ui_btnIncrease, LV_ALIGN_CENTER);

    ui_tempLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempLabel, 0);
    lv_obj_set_y(ui_tempLabel, -10);
    lv_obj_set_align(ui_tempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLabel, "25");
    lv_obj_set_style_text_font(ui_tempLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnDecrease = lv_imagebutton_create(ui_Screen1);
    lv_imagebutton_set_src(ui_btnDecrease, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_699983090, NULL);
    lv_imagebutton_set_src(ui_btnDecrease, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_699983090, NULL);
    lv_imagebutton_set_src(ui_btnDecrease, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imagebutton_set_src(ui_btnDecrease, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imagebutton_set_src(ui_btnDecrease, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imagebutton_set_src(ui_btnDecrease, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_btnDecrease, 32);
    lv_obj_set_height(ui_btnDecrease, 32);
    lv_obj_set_x(ui_btnDecrease, -70);
    lv_obj_set_y(ui_btnDecrease, 55);
    lv_obj_set_align(ui_btnDecrease, LV_ALIGN_CENTER);

    ui_labelActTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelActTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelActTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelActTemp, 0);
    lv_obj_set_y(ui_labelActTemp, 20);
    lv_obj_set_align(ui_labelActTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelActTemp, "00");
    lv_obj_set_style_text_color(ui_labelActTemp, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelActTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelActTemp, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 50);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 0);
    lv_obj_set_y(ui_Button1, 85);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x00FFA0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button1, lv_color_hex(0x49FA7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Button1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Button1, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button1, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_arcTempSettings, ui_event_arcTempSettings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnIncrease, ui_event_btnIncrease, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnDecrease, ui_event_btnDecrease, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
