// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: roundTest

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern void ui_event_arcTempSettings(lv_event_t * e);
extern lv_obj_t * ui_arcTempSettings;
extern lv_obj_t * ui_hidePanel;
extern void ui_event_btnIncrease(lv_event_t * e);
extern lv_obj_t * ui_btnIncrease;
extern lv_obj_t * ui_tempLabel;
extern void ui_event_btnDecrease(lv_event_t * e);
extern lv_obj_t * ui_btnDecrease;
extern lv_obj_t * ui_labelActTemp;
extern lv_obj_t * ui_Button1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

