// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: roundTest

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ArcMoistLevel = lv_arc_create(ui_Screen3);
    lv_obj_set_width(ui_ArcMoistLevel, 200);
    lv_obj_set_height(ui_ArcMoistLevel, 200);
    lv_obj_set_x(ui_ArcMoistLevel, -2);
    lv_obj_set_y(ui_ArcMoistLevel, -2);
    lv_obj_set_align(ui_ArcMoistLevel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArcMoistLevel, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_arc_set_value(ui_ArcMoistLevel, 50);
    lv_arc_set_bg_angles(ui_ArcMoistLevel, 0, 80);
    lv_arc_set_rotation(ui_ArcMoistLevel, 260);
    lv_obj_set_style_arc_rounded(ui_ArcMoistLevel, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcMoistLevel, lv_color_hex(0x09DFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcMoistLevel, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcMoistLevel, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcMoistLevel, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcMoistLevel, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ArcMoistLevel, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ArcMoistLevel, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ArcMoistLevel, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ArcMoistLevel, LV_BORDER_SIDE_FULL, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Roller2 = lv_roller_create(ui_Screen3);
    lv_roller_set_options(ui_Roller2, "FEEDER\nLIGHT\nHEATER\nMOISTURE", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_Roller2, 4, LV_ANIM_OFF);
    lv_obj_set_height(ui_Roller2, 50);
    lv_obj_set_width(ui_Roller2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller2, -55);
    lv_obj_set_y(ui_Roller2, 0);
    lv_obj_set_align(ui_Roller2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Roller2, LV_OBJ_FLAG_PRESS_LOCK);      /// Flags
    lv_obj_set_style_text_align(ui_Roller2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Roller2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Roller2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Roller2, 20, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller2, lv_color_hex(0x333333), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller2, 70, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Roller2, false, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_ButtonRollerUp = lv_button_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonRollerUp, 30);
    lv_obj_set_height(ui_ButtonRollerUp, 30);
    lv_obj_set_x(ui_ButtonRollerUp, -50);
    lv_obj_set_y(ui_ButtonRollerUp, -45);
    lv_obj_set_align(ui_ButtonRollerUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRollerUp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonRollerUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonRollerUp, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonRollerUp, lv_color_hex(0xD0D0D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonRollerUp, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBtnUp = lv_label_create(ui_ButtonRollerUp);
    lv_obj_set_width(ui_LabelBtnUp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnUp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBtnUp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnUp, ">");

    ui_ButtonRollerUp1 = lv_button_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonRollerUp1, 30);
    lv_obj_set_height(ui_ButtonRollerUp1, 30);
    lv_obj_set_x(ui_ButtonRollerUp1, -50);
    lv_obj_set_y(ui_ButtonRollerUp1, 50);
    lv_obj_set_align(ui_ButtonRollerUp1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRollerUp1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonRollerUp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonRollerUp1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonRollerUp1, lv_color_hex(0xD0D0D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonRollerUp1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBtnDown = lv_label_create(ui_ButtonRollerUp1);
    lv_obj_set_width(ui_LabelBtnDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBtnDown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnDown, ">");

    ui_SwitchMoistOnOff = lv_switch_create(ui_Screen3);
    lv_obj_set_width(ui_SwitchMoistOnOff, 50);
    lv_obj_set_height(ui_SwitchMoistOnOff, 25);
    lv_obj_set_x(ui_SwitchMoistOnOff, 85);
    lv_obj_set_y(ui_SwitchMoistOnOff, 0);
    lv_obj_set_align(ui_SwitchMoistOnOff, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SwitchMoistOnOff, lv_color_hex(0xFF8D01), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchMoistOnOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SwitchMoistOnOff, lv_color_hex(0x1AFF58), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SwitchMoistOnOff, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_SwitchMoistOnOff, lv_color_hex(0xD2D2D2), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchMoistOnOff, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SwitchMoistOnOff, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SwitchMoistOnOff, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SwitchMoistOnOff, 3, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelMoistOnOff = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelMoistOnOff, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMoistOnOff, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMoistOnOff, 43);
    lv_obj_set_y(ui_LabelMoistOnOff, 1);
    lv_obj_set_align(ui_LabelMoistOnOff, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMoistOnOff, "I / O");
    lv_obj_set_style_text_font(ui_LabelMoistOnOff, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableMoisture = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LableMoisture, 35);
    lv_obj_set_height(ui_LableMoisture, 22);
    lv_obj_set_x(ui_LableMoisture, 37);
    lv_obj_set_y(ui_LableMoisture, -54);
    lv_obj_set_align(ui_LableMoisture, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LableMoisture, "50");
    lv_obj_set_style_text_align(ui_LableMoisture, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableMoisture, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LableMoisture, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LableMoisture, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LableMoisture, 70, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMoistPrecentSign = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelMoistPrecentSign, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMoistPrecentSign, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMoistPrecentSign, 2);
    lv_obj_set_y(ui_LabelMoistPrecentSign, -56);
    lv_obj_set_align(ui_LabelMoistPrecentSign, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMoistPrecentSign, "%");

    ui_SlidetMoistureVolume = lv_slider_create(ui_Screen3);
    lv_slider_set_range(ui_SlidetMoistureVolume, 0, 10);
    lv_slider_set_value(ui_SlidetMoistureVolume, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SlidetMoistureVolume) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SlidetMoistureVolume, 10, LV_ANIM_OFF);
    lv_obj_set_width(ui_SlidetMoistureVolume, 84);
    lv_obj_set_height(ui_SlidetMoistureVolume, 10);
    lv_obj_set_x(ui_SlidetMoistureVolume, 53);
    lv_obj_set_y(ui_SlidetMoistureVolume, 46);
    lv_obj_set_align(ui_SlidetMoistureVolume, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SlidetMoistureVolume, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SlidetMoistureVolume, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SlidetMoistureVolume, lv_color_hex(0x89FFFE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SlidetMoistureVolume, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SlidetMoistureVolume, lv_color_hex(0x000DFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SlidetMoistureVolume, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SlidetMoistureVolume, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SlidetMoistureVolume, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SlidetMoistureVolume, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SlidetMoistureVolume, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_SlidetMoistureVolume, &ui_img_water_drop_24dp_d9d9d9_fill0_wght600_grad0_opsz24_png,
                                  LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SlidetMoistureVolume, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SlidetMoistureVolume, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SlidetMoistureVolume,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SlidetMoistureVolume,
                                                                                  lv_obj_get_style_pad_right(ui_SlidetMoistureVolume, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_SliderPumpPower = lv_slider_create(ui_Screen3);
    lv_slider_set_range(ui_SliderPumpPower, 0, 255);
    lv_slider_set_value(ui_SliderPumpPower, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderPumpPower) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderPumpPower, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderPumpPower, 84);
    lv_obj_set_height(ui_SliderPumpPower, 10);
    lv_obj_set_x(ui_SliderPumpPower, 26);
    lv_obj_set_y(ui_SliderPumpPower, 75);
    lv_obj_set_align(ui_SliderPumpPower, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderPumpPower, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPumpPower, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderPumpPower, lv_color_hex(0xA7FF89), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPumpPower, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderPumpPower, lv_color_hex(0xFFA600), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SliderPumpPower, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SliderPumpPower, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SliderPumpPower, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SliderPumpPower, lv_color_hex(0xD96666), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SliderPumpPower, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SliderPumpPower, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SliderPumpPower, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderPumpPower, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPumpPower, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_SliderPumpPower, &ui_img_bolt_24dp_d9d9d9_fill0_wght600_grad0_opsz24_png,
                                  LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SliderPumpPower, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SliderPumpPower,
                                                                                                      lv_obj_get_style_pad_right(ui_SliderPumpPower, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_LabelActualMoist = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelActualMoist, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelActualMoist, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelActualMoist, 37);
    lv_obj_set_y(ui_LabelActualMoist, -27);
    lv_obj_set_align(ui_LabelActualMoist, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelActualMoist, "00");
    lv_obj_set_style_text_color(ui_LabelActualMoist, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelActualMoist, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ArcMoistLevel, ui_event_ArcMoistLevel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}
